### ISSUE TITLE
Janus API 15 < 16 Build

### ISSUE THREAD

**Issue by calvincs** [mquander/janus-plugin-sfu#97]
After building the plugin and installing, I am receiving the following message after starting Janus with the plugin:

```
Plugins folder: /opt/janus/lib/janus/plugins
Loading plugin 'libjanus_plugin_sfu.so'...
Sessions watchdog started
Joining Janus requests handler thread
[ERR] [janus.c:main:5471] The 'janus.plugin.sfu' plugin was compiled against an older version of the API (15 < 16), skipping it: update it to enable it again
```

Current Janus server build:
```
root@janus:~/janus-plugin-sfu# /opt/janus/bin/janus -v
Janus commit: 7c83c093e05400d3c18e0cac08f1b797e35dfe4f
Compiled on:  Mon Feb  7 04:15:10 UTC 2022
```

Is this plugin being maintained anymore, will this be updated?

Thanks in advance!

**Comment by vincentfretin** [comment]
Hi @calvincs see https://github.com/networked-aframe/naf-janus-adapter/pull/23

**Comment by calvincs** [comment]
Awesome, thanks @vincentfretin 
So we are just waiting for things to merge and we should be good to go then?
Assuming I read those threads correctly.

**Comment by vincentfretin** [comment]
You have several possibilities, you can use an older janus-gateway version like v0.11.1 that was properly working, or use the latest 0.x branch but revert the janus-gateway commit that introduced the API change like I explained in the PR, or wait that I do the forks of janus-plugin-rs and janus-plugin-sfu and do the required changes in a new PR for those two packages, but no ETA for that. You can also just follow the install instructions with the changes in my PR with my janus-gateway fork where I already reverted the commit.

**Comment by calvincs** [comment]
Sounds great!  Thanks @vincentfretin I will close this out and keep an eye on progress.
It's my hope that I and others can help you maintain these components in the future. Anything we can do, please let us know.
